# Generated by Django 4.1.1 on 2022-09-09 05:46

from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProbabilityDistribution",
            fields=[
                (
                    "id",
                    hashid_field.field.HashidAutoField(
                        alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
                        min_length=7,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("xaxis_name", models.CharField(max_length=60)),
                ("lower_bound", models.FloatField()),
                ("upper_bound", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="NormalDist",
            fields=[
                (
                    "id",
                    hashid_field.field.HashidAutoField(
                        alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
                        min_length=7,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("mean", models.FloatField()),
                ("std", models.FloatField()),
                ("weight", models.FloatField()),
                (
                    "probabilitydistribution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="normal_distributions",
                        to="distributions.probabilitydistribution",
                    ),
                ),
            ],
        ),
    ]
